INSERT INTO USER (ID, VERSION, EMAIL, NAME, AGE, CITY, PASSWORD, DATE, ROLE) VALUES (10, 0, 'admin@admin.com', 'administrator', null, null, 'admin', SYSDATE, 'ADMIN');
INSERT INTO USER (ID, VERSION, EMAIL, NAME, AGE, CITY, PASSWORD, DATE, ROLE) VALUES (11, 0, 'nagymark@java.com', 'Nagy Mark', 21, 'Budapest', '1234', SYSDATE, 'USER');
INSERT INTO NEWS (ID, VERSION, DATE, DISLIKES, LIKES, TEXT, USER_ID) VALUES(20, 0, SYSDATE, 3, 5, 'ez egy news', 11);
INSERT INTO COMMENT (ID, VERSION, TEXT, LIKES, DISLIKES, DATE, NEWS_ID, USER_ID) VALUES (30, 0, 'comment', 2, 0, SYSDATE, 20, 10);