
INSERT INTO USER (ID, VERSION, EMAIL, NAME, AGE, CITY, PASSWORD, DATE, ROLE) VALUES (9000, 0, 'admin@admin.com', 'admin', null, null, 'admin', SYSDATE, 'ADMIN');
INSERT INTO USER (ID, VERSION, EMAIL, NAME, AGE, CITY, PASSWORD, DATE, ROLE) VALUES (8999, 0, 'nagymark@java.com', 'Nagy Márk', 21, 'Budapest', '1234', SYSDATE, 'USER');
INSERT INTO NEWS (ID, VERSION, DATE, DISLIKES, LIKES, TEXT, USER_ID) VALUES(2000, 0, SYSDATE, 3, 5, 'ez egy news', 8999);
INSERT INTO COMMENT (ID, VERSION, TEXT, LIKES, DISLIKES, DATE, NEWS_ID, USER_ID) VALUES (3000, 0, 'comment', 2, 0, SYSDATE, 2000, 9000);